version: '3.8'

services:
  minecraft:
    build: .
    container_name: forge-minecraft
    ports:
      - "25565:25565"
    volumes:
      - ./mods:/minecraft/mods
      - ./config:/minecraft/config
      - ./world:/minecraft/world
    restart: unless-stopped
